#FROM registry.access.redhat.com/rhel7.5
FROM centos:7.5.1804

LABEL maintainer="cesar.avila@dxc.com"
LABEL "Image"="dxclatam/mqha" \
      "Version"="1.1"
LABEL "ProductName"="IBM MQ Advanced" \
      "ProductVersion"="9.0.5"

# URL Para descargar el Producto
ARG MQ_URL=https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/mqadv_dev905_linux_x86-64.tar.gz

# Paquetes de MQ para descargar
#ARG MQ_PACKAGES="ibmmq-server ibmmq-java ibmmq-jre ibmmq-gskit ibmmq-web ibmmq-msg"
ARG MQ_PACKAGES="MQSeriesRuntime-*.rpm MQSeriesServer-*.rpm MQSeriesJava*.rpm MQSeriesJRE*.rpm MQSeriesGSKit*.rpm MQSeriesMsg*.rpm MQSeriesSamples*.rpm MQSeriesAMS-*.rpm"

# Instalacion Sistema Operativo
RUN yum -y install \
    bash \
    ca-certificates \
    file \
    coreutils \
    curl \
    net-tools \
    bind-utils \
    tar zip \
    findutils \
    grep && \
    yum -y update

    # Descargar MQ
RUN DIR_EXTRACT=/tmp/mq \
    mkdir -p ${DIR_EXTRACT} \
    cd ${DIR_EXTRACT} && \
    curl -LO $MQ_URL

    # Descomprimir archivo descarga
RUN tar -zvxf ./*.tar.gz && \
    # Remover escombros de la descarga
    yum clean all && \
    # Se crea el usuario de servicio y se le asignan privilegios
    groupadd --gid 888 mqm && \
    useradd --uid 888 --gid mqm mqm && \
    usermod -aG mqm root

    # Instala MQ y acepta la licencia
RUN DIR_RPM=$(find ${DIR_EXTRACT} -name "*.rpm" -printf "%h\n" | sort -u | head -1) && \
    MQLICENSE=$(find ${DIR_EXTRACT} -name "mqlicense.sh") && \
    ${MQLICENSE} -text_only -accept && \
    cd $DIR_RPM && \
    yum install -y $MQ_PACKAGES

    # Limpia escombros
RUN find /opt/mqm -name '*.tar.gz' -delete && \
    /opt/mqm/bin/setmqinst -p /opt/mqm -i && \
    # Clean up all the downloaded files
    #rm -f /etc/apt/sources.list.d/IBM_MQ.list \
    rm -f $DIR_RPM \
    rm -rf ${DIR_EXTRACT}

COPY /mq_shell/*.sh /usr/local/bin/
COPY /descriptor/*.mqsc /etc/mqm/
COPY /mq_shell/admin.json /etc/mqm/

##COPY mq-dev-config /etc/mqm/mq-dev-config

RUN chmod +x /usr/local/bin/*.sh

# Expose port 9443 for the web console
EXPOSE 1414 9443

ENV LANG=en_US.UTF-8;es_CL.UTF-8

ENTRYPOINT ["mq.sh"]
