version: '3.4'
services:
  mq:
    image: dxclatam/mqha:1.1
    build:
      context: .
      dockerfile: Dockerfile-mq
    restart: always
    ports:
    - "1414:1414"
    - "9443:9443"
    environment:
      MQ_ENV: prod
      MQ_QMGR_NAME: QMLTP01
      port: 9443
    volumes:
      - varmqm:/var/mqm
volumes:
  varmqm:
networks:
  overlay:
